services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: simplepassword
      DOCKER_INFLUXDB_INIT_ORG: risklab
      DOCKER_INFLUXDB_INIT_BUCKET: market
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: evensimplertoken
      
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_PANELS_DISABLE_SANITIZE_HTML=true

volumes:
  influxdb-data:
  grafana-data: